//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JourneyToTheWest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JOURNEYTOTHEWESTEntities : DbContext
    {
        public JOURNEYTOTHEWESTEntities()
            : base("name=JOURNEYTOTHEWESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Cast> Casts { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentStatu> EquipmentStatus { get; set; }
        public virtual DbSet<EquipmentUsingHistory> EquipmentUsingHistories { get; set; }
        public virtual DbSet<Impersonation> Impersonations { get; set; }
        public virtual DbSet<RecordHistory> RecordHistories { get; set; }
        public virtual DbSet<Scene> Scenes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
