//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JourneyToTheWest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentUsingHistory
    {
        public int EquipmentId { get; set; }
        public int SceneId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Scene Scene { get; set; }
    }
}
