//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JourneyToTheWest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impersonation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Impersonation()
        {
            this.RecordHistories = new HashSet<RecordHistory>();
        }
    
        public int Id { get; set; }
        public string DefaultCastId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Cast Cast { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordHistory> RecordHistories { get; set; }
    }
}
