//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JourneyToTheWest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordHistory
    {
        public int Id { get; set; }
        public Nullable<int> SceneId { get; set; }
        public Nullable<int> ImpersonationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AssignedCastId { get; set; }
    
        public virtual Cast Cast { get; set; }
        public virtual Impersonation Impersonation { get; set; }
        public virtual Scene Scene { get; set; }
    }
}
